/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./components/ui/avatar/AvatarImage.vue')['default']
    BiliAuthCodeSelector: typeof import('./components/BiliAuthCodeSelector.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Combobox: typeof import('./components/ui/combobox/Combobox.vue')['default']
    ComboboxAnchor: typeof import('./components/ui/combobox/ComboboxAnchor.vue')['default']
    ComboboxEmpty: typeof import('./components/ui/combobox/ComboboxEmpty.vue')['default']
    ComboboxGroup: typeof import('./components/ui/combobox/ComboboxGroup.vue')['default']
    ComboboxInput: typeof import('./components/ui/combobox/ComboboxInput.vue')['default']
    ComboboxItem: typeof import('./components/ui/combobox/ComboboxItem.vue')['default']
    ComboboxList: typeof import('./components/ui/combobox/ComboboxList.vue')['default']
    ComboboxSeparator: typeof import('./components/ui/combobox/ComboboxSeparator.vue')['default']
    ComboboxTrigger: typeof import('./components/ui/combobox/ComboboxTrigger.vue')['default']
    ConfigPanel: typeof import('./components/ConfigPanel.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    OrderCard: typeof import('./components/OrderCard.vue')['default']
    OrderList: typeof import('./components/OrderList.vue')['default']
    Popover: typeof import('./components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./components/ui/popover/PopoverTrigger.vue')['default']
    Ranking: typeof import('./components/Ranking.vue')['default']
    Skeleton: typeof import('./components/ui/skeleton/Skeleton.vue')['default']
    Slider: typeof import('./components/ui/slider/Slider.vue')['default']
    Switch: typeof import('./components/ui/switch/Switch.vue')['default']
    Tabs: typeof import('./components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/tabs/TabsTrigger.vue')['default']
  }
}
